version: '3.8'
services:
  spring-boot-app:
    image: spring-mysql-test:latest
    restart: always
    ports:
      - "0.0.0.0:8081:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/api_etudiant
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - spring-mysql-network
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_etudiant
      MYSQL_ROOT_USERNAME: root
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - api_etudiant:/var/lib/mysql
    networks:
      - spring-mysql-network
networks:
  spring-mysql-network:

volumes:
  api_etudiant: